# Server Configuration
server.port=8080
server.address=0.0.0.0
spring.application.name=thecheatschoolserver

# Sanity Configuration
sanity.project-id=4x6wdy47
sanity.dataset=production
sanity.api-version=2024-01-01

# CORS Configuration
cors.allowed-origins=http://localhost:5173,https://talhas-projects-the-cheat-schoole210in1357g0.vercel.app,https://www.thecheatschool.com
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed-headers=*
cors.allow-credentials=true

# Cache Configuration
spring.cache.type=caffeine
spring.cache.cache-names=blogs
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=10m

# Database Configuration
spring.datasource.url=jdbc:postgresql://ep-jolly-grass-ah00qd3s-pooler.c-3.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_w9xPElVhL7QO
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Resend Configuration
resend.api.key=re_edw2z9QA_KhfBF6x9iRtAdGFEHpDq6d59
contact.recipient.email=thecheatschoolcode@gmail.com

# Logging
logging.level.com.thecheatschool.server=INFO
logging.level.com.thecheatschool.server.service=DEBUG