# Server Configuration
server.port=8080
spring.application.name=thecheatschoolserver

# Sanity Configuration
sanity.project-id=4x6wdy47
sanity.dataset=production
sanity.api-version=2024-01-01

# CORS Configuration
cors.allowed-origins=http://localhost:5173,https://your-vercel-app.vercel.app

# Logging
logging.level.com.thecheatschool.thecheatschool.server=INFO
logging.level.com.thecheatschool..thecheatschool.server.service=DEBUG